on:
  workflow_call:
    inputs:
      upgrade-branch-title:
        type: string
        default: Run `cargo-msrv`
      upgrade-branch-name:
        type: string
        default: cargo-msrv
      working-directory:
        type: string
        default: "."
      commit-message:
        type: string
        default: run cargo-msrv

jobs:
  cargo-msrv-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
        env:
          # renovate: datasource=github-tags depName=rust-lang/rust versioning=rust-release-channel
          RUST_VERSION: 1.95.0
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - uses: cargo-bins/cargo-binstall@c0ae9335b22cb4f297cdd1df049cd87bf2aa223f # main
      - run: cargo binstall --force cargo-msrv@${{ env.CARGO_MSRV_VERSION }}
        env:
          # renovate: datasource=crate depName=cargo-msrv versioning=loose
          CARGO_MSRV_VERSION: 0.19.3
          
      - run: |
          cat Cargo.toml | sed -z 's/rust-version.*\n//mg' > Cargo2.toml
          mv Cargo2.toml Cargo.toml
          
      - run: cargo msrv find --write-msrv
      
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: ${{ inputs.commit-message }}
          title: ${{ inputs.upgrade-branch-title }}
          branch: ${{ inputs.upgrade-branch-name }}
